# Generated by Django 5.1.1 on 2026-03-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colormap', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RasterTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tif_file', models.CharField(max_length=500)),
                ('png_file', models.CharField(max_length=500)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('extent_left', models.FloatField()),
                ('extent_bottom', models.FloatField()),
                ('extent_right', models.FloatField()),
                ('extent_top', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='SDGtunisia.dataset')),
            ],
        ),
    ]
