# Generated by Django 5.1.1 on 2026-03-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDGtunisia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastertile',
            name='index_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rastertile',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rastertile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDGtunisia.dataset'),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='png_file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rastertile',
            name='tif_file',
            field=models.CharField(max_length=255),
        ),
    ]
